/********************************************************************************
** Form generated from reading UI file 'DigitalMapForWHU.ui'
**
** Created by: Qt User Interface Compiler version 5.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DIGITALMAPFORWHU_H
#define UI_DIGITALMAPFORWHU_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_DigitalMapForWHUClass
{
public:
    QAction *actionquery;
    QAction *actionexit;
    QAction *actionroute;
    QAction *actionaddress;
    QWidget *centralWidget;
    QToolButton *office_1;
    QToolButton *canteen_1;
    QToolButton *dorm_1;
    QToolButton *teaching_1;
    QToolButton *canteen_2;
    QToolButton *canteen_3;
    QToolButton *canteen_4;
    QToolButton *canteen_5;
    QToolButton *canteen_6;
    QToolButton *canteen_7;
    QToolButton *canteen_8;
    QToolButton *canteen_9;
    QToolButton *canteen_10;
    QToolButton *canteen_11;
    QToolButton *canteen_12;
    QToolButton *canteen_13;
    QToolButton *canteen_14;
    QToolButton *canteen_15;
    QToolButton *canteen_16;
    QToolButton *canteen_17;
    QToolButton *canteen_18;
    QToolButton *canteen_19;
    QToolButton *canteen_20;
    QToolButton *office_2;
    QToolButton *office_3;
    QToolButton *office_4;
    QToolButton *office_5;
    QToolButton *office_6;
    QToolButton *office_7;
    QToolButton *office_8;
    QToolButton *office_9;
    QToolButton *office_10;
    QToolButton *office_11;
    QToolButton *office_12;
    QToolButton *office_13;
    QToolButton *office_14;
    QToolButton *office_15;
    QToolButton *office_16;
    QToolButton *office_17;
    QToolButton *office_18;
    QToolButton *office_19;
    QToolButton *office_20;
    QToolButton *teaching_2;
    QToolButton *teaching_3;
    QToolButton *teaching_4;
    QToolButton *teaching_5;
    QToolButton *teaching_6;
    QToolButton *teaching_7;
    QToolButton *teaching_8;
    QToolButton *teaching_9;
    QToolButton *teaching_10;
    QToolButton *teaching_11;
    QToolButton *teaching_12;
    QToolButton *teaching_13;
    QToolButton *teaching_14;
    QToolButton *teaching_15;
    QToolButton *teaching_16;
    QToolButton *teaching_17;
    QToolButton *teaching_18;
    QToolButton *teaching_19;
    QToolButton *teaching_20;
    QToolButton *dorm_2;
    QToolButton *dorm_3;
    QToolButton *dorm_4;
    QToolButton *dorm_5;
    QToolButton *dorm_6;
    QToolButton *dorm_7;
    QToolButton *dorm_8;
    QToolButton *dorm_9;
    QToolButton *dorm_10;
    QToolButton *dorm_11;
    QToolButton *dorm_12;
    QToolButton *dorm_13;
    QToolButton *dorm_14;
    QToolButton *dorm_15;
    QToolButton *dorm_16;
    QToolButton *dorm_17;
    QToolButton *dorm_18;
    QToolButton *dorm_19;
    QToolButton *dorm_20;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *DigitalMapForWHUClass)
    {
        if (DigitalMapForWHUClass->objectName().isEmpty())
            DigitalMapForWHUClass->setObjectName(QStringLiteral("DigitalMapForWHUClass"));
        DigitalMapForWHUClass->resize(2000, 1900);
        actionquery = new QAction(DigitalMapForWHUClass);
        actionquery->setObjectName(QStringLiteral("actionquery"));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/\346\226\260\345\211\215\347\274\200/Resources/search_48px_1200688_easyicon.net.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionquery->setIcon(icon);
        actionexit = new QAction(DigitalMapForWHUClass);
        actionexit->setObjectName(QStringLiteral("actionexit"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/\346\226\260\345\211\215\347\274\200/Resources/exit_64.385542168675px_1201055_easyicon.net.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionexit->setIcon(icon1);
        actionroute = new QAction(DigitalMapForWHUClass);
        actionroute->setObjectName(QStringLiteral("actionroute"));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/\346\226\260\345\211\215\347\274\200/Resources/route_63.640449438202px_1201221_easyicon.net.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionroute->setIcon(icon2);
        actionaddress = new QAction(DigitalMapForWHUClass);
        actionaddress->setObjectName(QStringLiteral("actionaddress"));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/\346\226\260\345\211\215\347\274\200/Resources/map_location_68.952380952381px_1201146_easyicon.net.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionaddress->setIcon(icon3);
        centralWidget = new QWidget(DigitalMapForWHUClass);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        office_1 = new QToolButton(centralWidget);
        office_1->setObjectName(QStringLiteral("office_1"));
        office_1->setEnabled(true);
        office_1->setGeometry(QRect(940, 120, 50, 50));
        office_1->setAutoFillBackground(false);
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/\346\226\260\345\211\215\347\274\200/Resources/office_block_1945px_1202687_easyicon.net.png"), QSize(), QIcon::Normal, QIcon::Off);
        office_1->setIcon(icon4);
        office_1->setIconSize(QSize(40, 40));
        office_1->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_1 = new QToolButton(centralWidget);
        canteen_1->setObjectName(QStringLiteral("canteen_1"));
        canteen_1->setEnabled(true);
        canteen_1->setGeometry(QRect(724, 120, 50, 50));
        canteen_1->setAutoFillBackground(false);
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/\346\226\260\345\211\215\347\274\200/Resources/Restaurant_Blue_256px_1078998_easyicon.net.png"), QSize(), QIcon::Normal, QIcon::Off);
        canteen_1->setIcon(icon5);
        canteen_1->setIconSize(QSize(40, 40));
        canteen_1->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_1 = new QToolButton(centralWidget);
        dorm_1->setObjectName(QStringLiteral("dorm_1"));
        dorm_1->setEnabled(true);
        dorm_1->setGeometry(QRect(820, 180, 50, 50));
        dorm_1->setAutoFillBackground(false);
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/\346\226\260\345\211\215\347\274\200/Resources/home_176px_1201102_easyicon.net.png"), QSize(), QIcon::Normal, QIcon::Off);
        dorm_1->setIcon(icon6);
        dorm_1->setIconSize(QSize(40, 40));
        dorm_1->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_1 = new QToolButton(centralWidget);
        teaching_1->setObjectName(QStringLiteral("teaching_1"));
        teaching_1->setEnabled(true);
        teaching_1->setGeometry(QRect(810, 120, 50, 50));
        teaching_1->setAutoFillBackground(false);
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/\346\226\260\345\211\215\347\274\200/Resources/building_158px_1185575_easyicon.net.png"), QSize(), QIcon::Normal, QIcon::Off);
        teaching_1->setIcon(icon7);
        teaching_1->setIconSize(QSize(40, 40));
        teaching_1->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_2 = new QToolButton(centralWidget);
        canteen_2->setObjectName(QStringLiteral("canteen_2"));
        canteen_2->setEnabled(true);
        canteen_2->setGeometry(QRect(80, 30, 50, 50));
        canteen_2->setAutoFillBackground(false);
        canteen_2->setIcon(icon5);
        canteen_2->setIconSize(QSize(40, 40));
        canteen_2->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_3 = new QToolButton(centralWidget);
        canteen_3->setObjectName(QStringLiteral("canteen_3"));
        canteen_3->setEnabled(true);
        canteen_3->setGeometry(QRect(250, 70, 50, 50));
        canteen_3->setAutoFillBackground(false);
        canteen_3->setIcon(icon5);
        canteen_3->setIconSize(QSize(40, 40));
        canteen_3->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_4 = new QToolButton(centralWidget);
        canteen_4->setObjectName(QStringLiteral("canteen_4"));
        canteen_4->setEnabled(true);
        canteen_4->setGeometry(QRect(230, 130, 50, 50));
        canteen_4->setAutoFillBackground(false);
        canteen_4->setIcon(icon5);
        canteen_4->setIconSize(QSize(40, 40));
        canteen_4->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_5 = new QToolButton(centralWidget);
        canteen_5->setObjectName(QStringLiteral("canteen_5"));
        canteen_5->setEnabled(true);
        canteen_5->setGeometry(QRect(0, 180, 50, 50));
        canteen_5->setAutoFillBackground(false);
        canteen_5->setIcon(icon5);
        canteen_5->setIconSize(QSize(40, 40));
        canteen_5->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_6 = new QToolButton(centralWidget);
        canteen_6->setObjectName(QStringLiteral("canteen_6"));
        canteen_6->setEnabled(true);
        canteen_6->setGeometry(QRect(310, 90, 50, 50));
        canteen_6->setAutoFillBackground(false);
        canteen_6->setIcon(icon5);
        canteen_6->setIconSize(QSize(40, 40));
        canteen_6->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_7 = new QToolButton(centralWidget);
        canteen_7->setObjectName(QStringLiteral("canteen_7"));
        canteen_7->setEnabled(true);
        canteen_7->setGeometry(QRect(410, 30, 50, 50));
        canteen_7->setAutoFillBackground(false);
        canteen_7->setIcon(icon5);
        canteen_7->setIconSize(QSize(40, 40));
        canteen_7->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_8 = new QToolButton(centralWidget);
        canteen_8->setObjectName(QStringLiteral("canteen_8"));
        canteen_8->setEnabled(true);
        canteen_8->setGeometry(QRect(420, 30, 50, 50));
        canteen_8->setAutoFillBackground(false);
        canteen_8->setIcon(icon5);
        canteen_8->setIconSize(QSize(40, 40));
        canteen_8->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_9 = new QToolButton(centralWidget);
        canteen_9->setObjectName(QStringLiteral("canteen_9"));
        canteen_9->setEnabled(true);
        canteen_9->setGeometry(QRect(570, 30, 50, 50));
        canteen_9->setAutoFillBackground(false);
        canteen_9->setIcon(icon5);
        canteen_9->setIconSize(QSize(40, 40));
        canteen_9->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_10 = new QToolButton(centralWidget);
        canteen_10->setObjectName(QStringLiteral("canteen_10"));
        canteen_10->setEnabled(true);
        canteen_10->setGeometry(QRect(540, 40, 50, 50));
        canteen_10->setAutoFillBackground(false);
        canteen_10->setIcon(icon5);
        canteen_10->setIconSize(QSize(40, 40));
        canteen_10->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_11 = new QToolButton(centralWidget);
        canteen_11->setObjectName(QStringLiteral("canteen_11"));
        canteen_11->setEnabled(true);
        canteen_11->setGeometry(QRect(490, 30, 50, 50));
        canteen_11->setAutoFillBackground(false);
        canteen_11->setIcon(icon5);
        canteen_11->setIconSize(QSize(40, 40));
        canteen_11->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_12 = new QToolButton(centralWidget);
        canteen_12->setObjectName(QStringLiteral("canteen_12"));
        canteen_12->setEnabled(true);
        canteen_12->setGeometry(QRect(480, 40, 50, 50));
        canteen_12->setAutoFillBackground(false);
        canteen_12->setIcon(icon5);
        canteen_12->setIconSize(QSize(40, 40));
        canteen_12->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_13 = new QToolButton(centralWidget);
        canteen_13->setObjectName(QStringLiteral("canteen_13"));
        canteen_13->setEnabled(true);
        canteen_13->setGeometry(QRect(490, 50, 50, 50));
        canteen_13->setAutoFillBackground(false);
        canteen_13->setIcon(icon5);
        canteen_13->setIconSize(QSize(40, 40));
        canteen_13->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_14 = new QToolButton(centralWidget);
        canteen_14->setObjectName(QStringLiteral("canteen_14"));
        canteen_14->setEnabled(true);
        canteen_14->setGeometry(QRect(500, 60, 50, 50));
        canteen_14->setAutoFillBackground(false);
        canteen_14->setIcon(icon5);
        canteen_14->setIconSize(QSize(40, 40));
        canteen_14->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_15 = new QToolButton(centralWidget);
        canteen_15->setObjectName(QStringLiteral("canteen_15"));
        canteen_15->setEnabled(true);
        canteen_15->setGeometry(QRect(510, 70, 50, 50));
        canteen_15->setAutoFillBackground(false);
        canteen_15->setIcon(icon5);
        canteen_15->setIconSize(QSize(40, 40));
        canteen_15->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_16 = new QToolButton(centralWidget);
        canteen_16->setObjectName(QStringLiteral("canteen_16"));
        canteen_16->setEnabled(true);
        canteen_16->setGeometry(QRect(520, 80, 50, 50));
        canteen_16->setAutoFillBackground(false);
        canteen_16->setIcon(icon5);
        canteen_16->setIconSize(QSize(40, 40));
        canteen_16->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_17 = new QToolButton(centralWidget);
        canteen_17->setObjectName(QStringLiteral("canteen_17"));
        canteen_17->setEnabled(true);
        canteen_17->setGeometry(QRect(530, 90, 50, 50));
        canteen_17->setAutoFillBackground(false);
        canteen_17->setIcon(icon5);
        canteen_17->setIconSize(QSize(40, 40));
        canteen_17->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_18 = new QToolButton(centralWidget);
        canteen_18->setObjectName(QStringLiteral("canteen_18"));
        canteen_18->setEnabled(true);
        canteen_18->setGeometry(QRect(540, 100, 50, 50));
        canteen_18->setAutoFillBackground(false);
        canteen_18->setIcon(icon5);
        canteen_18->setIconSize(QSize(40, 40));
        canteen_18->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_19 = new QToolButton(centralWidget);
        canteen_19->setObjectName(QStringLiteral("canteen_19"));
        canteen_19->setEnabled(true);
        canteen_19->setGeometry(QRect(550, 110, 50, 50));
        canteen_19->setAutoFillBackground(false);
        canteen_19->setIcon(icon5);
        canteen_19->setIconSize(QSize(40, 40));
        canteen_19->setToolButtonStyle(Qt::ToolButtonIconOnly);
        canteen_20 = new QToolButton(centralWidget);
        canteen_20->setObjectName(QStringLiteral("canteen_20"));
        canteen_20->setEnabled(true);
        canteen_20->setGeometry(QRect(560, 120, 50, 50));
        canteen_20->setAutoFillBackground(false);
        canteen_20->setIcon(icon5);
        canteen_20->setIconSize(QSize(40, 40));
        canteen_20->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_2 = new QToolButton(centralWidget);
        office_2->setObjectName(QStringLiteral("office_2"));
        office_2->setEnabled(true);
        office_2->setGeometry(QRect(1010, 80, 50, 50));
        office_2->setAutoFillBackground(false);
        office_2->setIcon(icon4);
        office_2->setIconSize(QSize(40, 40));
        office_2->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_3 = new QToolButton(centralWidget);
        office_3->setObjectName(QStringLiteral("office_3"));
        office_3->setEnabled(true);
        office_3->setGeometry(QRect(1020, 90, 50, 50));
        office_3->setAutoFillBackground(false);
        office_3->setIcon(icon4);
        office_3->setIconSize(QSize(40, 40));
        office_3->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_4 = new QToolButton(centralWidget);
        office_4->setObjectName(QStringLiteral("office_4"));
        office_4->setEnabled(true);
        office_4->setGeometry(QRect(1030, 100, 50, 50));
        office_4->setAutoFillBackground(false);
        office_4->setIcon(icon4);
        office_4->setIconSize(QSize(40, 40));
        office_4->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_5 = new QToolButton(centralWidget);
        office_5->setObjectName(QStringLiteral("office_5"));
        office_5->setEnabled(true);
        office_5->setGeometry(QRect(1040, 110, 50, 50));
        office_5->setAutoFillBackground(false);
        office_5->setIcon(icon4);
        office_5->setIconSize(QSize(40, 40));
        office_5->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_6 = new QToolButton(centralWidget);
        office_6->setObjectName(QStringLiteral("office_6"));
        office_6->setEnabled(true);
        office_6->setGeometry(QRect(1050, 120, 50, 50));
        office_6->setAutoFillBackground(false);
        office_6->setIcon(icon4);
        office_6->setIconSize(QSize(40, 40));
        office_6->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_7 = new QToolButton(centralWidget);
        office_7->setObjectName(QStringLiteral("office_7"));
        office_7->setEnabled(true);
        office_7->setGeometry(QRect(1060, 130, 50, 50));
        office_7->setAutoFillBackground(false);
        office_7->setIcon(icon4);
        office_7->setIconSize(QSize(40, 40));
        office_7->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_8 = new QToolButton(centralWidget);
        office_8->setObjectName(QStringLiteral("office_8"));
        office_8->setEnabled(true);
        office_8->setGeometry(QRect(1070, 140, 50, 50));
        office_8->setAutoFillBackground(false);
        office_8->setIcon(icon4);
        office_8->setIconSize(QSize(40, 40));
        office_8->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_9 = new QToolButton(centralWidget);
        office_9->setObjectName(QStringLiteral("office_9"));
        office_9->setEnabled(true);
        office_9->setGeometry(QRect(1080, 150, 50, 50));
        office_9->setAutoFillBackground(false);
        office_9->setIcon(icon4);
        office_9->setIconSize(QSize(40, 40));
        office_9->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_10 = new QToolButton(centralWidget);
        office_10->setObjectName(QStringLiteral("office_10"));
        office_10->setEnabled(true);
        office_10->setGeometry(QRect(1090, 160, 50, 50));
        office_10->setAutoFillBackground(false);
        office_10->setIcon(icon4);
        office_10->setIconSize(QSize(40, 40));
        office_10->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_11 = new QToolButton(centralWidget);
        office_11->setObjectName(QStringLiteral("office_11"));
        office_11->setEnabled(true);
        office_11->setGeometry(QRect(1100, 170, 50, 50));
        office_11->setAutoFillBackground(false);
        office_11->setIcon(icon4);
        office_11->setIconSize(QSize(40, 40));
        office_11->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_12 = new QToolButton(centralWidget);
        office_12->setObjectName(QStringLiteral("office_12"));
        office_12->setEnabled(true);
        office_12->setGeometry(QRect(1110, 180, 50, 50));
        office_12->setAutoFillBackground(false);
        office_12->setIcon(icon4);
        office_12->setIconSize(QSize(40, 40));
        office_12->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_13 = new QToolButton(centralWidget);
        office_13->setObjectName(QStringLiteral("office_13"));
        office_13->setEnabled(true);
        office_13->setGeometry(QRect(1120, 190, 50, 50));
        office_13->setAutoFillBackground(false);
        office_13->setIcon(icon4);
        office_13->setIconSize(QSize(40, 40));
        office_13->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_14 = new QToolButton(centralWidget);
        office_14->setObjectName(QStringLiteral("office_14"));
        office_14->setEnabled(true);
        office_14->setGeometry(QRect(1130, 200, 50, 50));
        office_14->setAutoFillBackground(false);
        office_14->setIcon(icon4);
        office_14->setIconSize(QSize(40, 40));
        office_14->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_15 = new QToolButton(centralWidget);
        office_15->setObjectName(QStringLiteral("office_15"));
        office_15->setEnabled(true);
        office_15->setGeometry(QRect(1140, 210, 50, 50));
        office_15->setAutoFillBackground(false);
        office_15->setIcon(icon4);
        office_15->setIconSize(QSize(40, 40));
        office_15->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_16 = new QToolButton(centralWidget);
        office_16->setObjectName(QStringLiteral("office_16"));
        office_16->setEnabled(true);
        office_16->setGeometry(QRect(1150, 220, 50, 50));
        office_16->setAutoFillBackground(false);
        office_16->setIcon(icon4);
        office_16->setIconSize(QSize(40, 40));
        office_16->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_17 = new QToolButton(centralWidget);
        office_17->setObjectName(QStringLiteral("office_17"));
        office_17->setEnabled(true);
        office_17->setGeometry(QRect(1160, 230, 50, 50));
        office_17->setAutoFillBackground(false);
        office_17->setIcon(icon4);
        office_17->setIconSize(QSize(40, 40));
        office_17->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_18 = new QToolButton(centralWidget);
        office_18->setObjectName(QStringLiteral("office_18"));
        office_18->setEnabled(true);
        office_18->setGeometry(QRect(1170, 240, 50, 50));
        office_18->setAutoFillBackground(false);
        office_18->setIcon(icon4);
        office_18->setIconSize(QSize(40, 40));
        office_18->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_19 = new QToolButton(centralWidget);
        office_19->setObjectName(QStringLiteral("office_19"));
        office_19->setEnabled(true);
        office_19->setGeometry(QRect(1180, 250, 50, 50));
        office_19->setAutoFillBackground(false);
        office_19->setIcon(icon4);
        office_19->setIconSize(QSize(40, 40));
        office_19->setToolButtonStyle(Qt::ToolButtonIconOnly);
        office_20 = new QToolButton(centralWidget);
        office_20->setObjectName(QStringLiteral("office_20"));
        office_20->setEnabled(true);
        office_20->setGeometry(QRect(1190, 260, 50, 50));
        office_20->setAutoFillBackground(false);
        office_20->setIcon(icon4);
        office_20->setIconSize(QSize(40, 40));
        office_20->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_2 = new QToolButton(centralWidget);
        teaching_2->setObjectName(QStringLiteral("teaching_2"));
        teaching_2->setEnabled(true);
        teaching_2->setGeometry(QRect(820, 120, 50, 50));
        teaching_2->setAutoFillBackground(false);
        teaching_2->setIcon(icon7);
        teaching_2->setIconSize(QSize(40, 40));
        teaching_2->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_3 = new QToolButton(centralWidget);
        teaching_3->setObjectName(QStringLiteral("teaching_3"));
        teaching_3->setEnabled(true);
        teaching_3->setGeometry(QRect(830, 130, 50, 50));
        teaching_3->setAutoFillBackground(false);
        teaching_3->setIcon(icon7);
        teaching_3->setIconSize(QSize(40, 40));
        teaching_3->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_4 = new QToolButton(centralWidget);
        teaching_4->setObjectName(QStringLiteral("teaching_4"));
        teaching_4->setEnabled(true);
        teaching_4->setGeometry(QRect(840, 140, 50, 50));
        teaching_4->setAutoFillBackground(false);
        teaching_4->setIcon(icon7);
        teaching_4->setIconSize(QSize(40, 40));
        teaching_4->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_5 = new QToolButton(centralWidget);
        teaching_5->setObjectName(QStringLiteral("teaching_5"));
        teaching_5->setEnabled(true);
        teaching_5->setGeometry(QRect(850, 150, 50, 50));
        teaching_5->setAutoFillBackground(false);
        teaching_5->setIcon(icon7);
        teaching_5->setIconSize(QSize(40, 40));
        teaching_5->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_6 = new QToolButton(centralWidget);
        teaching_6->setObjectName(QStringLiteral("teaching_6"));
        teaching_6->setEnabled(true);
        teaching_6->setGeometry(QRect(860, 160, 50, 50));
        teaching_6->setAutoFillBackground(false);
        teaching_6->setIcon(icon7);
        teaching_6->setIconSize(QSize(40, 40));
        teaching_6->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_7 = new QToolButton(centralWidget);
        teaching_7->setObjectName(QStringLiteral("teaching_7"));
        teaching_7->setEnabled(true);
        teaching_7->setGeometry(QRect(870, 170, 50, 50));
        teaching_7->setAutoFillBackground(false);
        teaching_7->setIcon(icon7);
        teaching_7->setIconSize(QSize(40, 40));
        teaching_7->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_8 = new QToolButton(centralWidget);
        teaching_8->setObjectName(QStringLiteral("teaching_8"));
        teaching_8->setEnabled(true);
        teaching_8->setGeometry(QRect(880, 180, 50, 50));
        teaching_8->setAutoFillBackground(false);
        teaching_8->setIcon(icon7);
        teaching_8->setIconSize(QSize(40, 40));
        teaching_8->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_9 = new QToolButton(centralWidget);
        teaching_9->setObjectName(QStringLiteral("teaching_9"));
        teaching_9->setEnabled(true);
        teaching_9->setGeometry(QRect(890, 190, 50, 50));
        teaching_9->setAutoFillBackground(false);
        teaching_9->setIcon(icon7);
        teaching_9->setIconSize(QSize(40, 40));
        teaching_9->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_10 = new QToolButton(centralWidget);
        teaching_10->setObjectName(QStringLiteral("teaching_10"));
        teaching_10->setEnabled(true);
        teaching_10->setGeometry(QRect(900, 200, 50, 50));
        teaching_10->setAutoFillBackground(false);
        teaching_10->setIcon(icon7);
        teaching_10->setIconSize(QSize(40, 40));
        teaching_10->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_11 = new QToolButton(centralWidget);
        teaching_11->setObjectName(QStringLiteral("teaching_11"));
        teaching_11->setEnabled(true);
        teaching_11->setGeometry(QRect(910, 210, 50, 50));
        teaching_11->setAutoFillBackground(false);
        teaching_11->setIcon(icon7);
        teaching_11->setIconSize(QSize(40, 40));
        teaching_11->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_12 = new QToolButton(centralWidget);
        teaching_12->setObjectName(QStringLiteral("teaching_12"));
        teaching_12->setEnabled(true);
        teaching_12->setGeometry(QRect(920, 220, 50, 50));
        teaching_12->setAutoFillBackground(false);
        teaching_12->setIcon(icon7);
        teaching_12->setIconSize(QSize(40, 40));
        teaching_12->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_13 = new QToolButton(centralWidget);
        teaching_13->setObjectName(QStringLiteral("teaching_13"));
        teaching_13->setEnabled(true);
        teaching_13->setGeometry(QRect(930, 230, 50, 50));
        teaching_13->setAutoFillBackground(false);
        teaching_13->setIcon(icon7);
        teaching_13->setIconSize(QSize(40, 40));
        teaching_13->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_14 = new QToolButton(centralWidget);
        teaching_14->setObjectName(QStringLiteral("teaching_14"));
        teaching_14->setEnabled(true);
        teaching_14->setGeometry(QRect(940, 240, 50, 50));
        teaching_14->setAutoFillBackground(false);
        teaching_14->setIcon(icon7);
        teaching_14->setIconSize(QSize(40, 40));
        teaching_14->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_15 = new QToolButton(centralWidget);
        teaching_15->setObjectName(QStringLiteral("teaching_15"));
        teaching_15->setEnabled(true);
        teaching_15->setGeometry(QRect(950, 250, 50, 50));
        teaching_15->setAutoFillBackground(false);
        teaching_15->setIcon(icon7);
        teaching_15->setIconSize(QSize(40, 40));
        teaching_15->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_16 = new QToolButton(centralWidget);
        teaching_16->setObjectName(QStringLiteral("teaching_16"));
        teaching_16->setEnabled(true);
        teaching_16->setGeometry(QRect(960, 260, 50, 50));
        teaching_16->setAutoFillBackground(false);
        teaching_16->setIcon(icon7);
        teaching_16->setIconSize(QSize(40, 40));
        teaching_16->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_17 = new QToolButton(centralWidget);
        teaching_17->setObjectName(QStringLiteral("teaching_17"));
        teaching_17->setEnabled(true);
        teaching_17->setGeometry(QRect(970, 270, 50, 50));
        teaching_17->setAutoFillBackground(false);
        teaching_17->setIcon(icon7);
        teaching_17->setIconSize(QSize(40, 40));
        teaching_17->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_18 = new QToolButton(centralWidget);
        teaching_18->setObjectName(QStringLiteral("teaching_18"));
        teaching_18->setEnabled(true);
        teaching_18->setGeometry(QRect(980, 280, 50, 50));
        teaching_18->setAutoFillBackground(false);
        teaching_18->setIcon(icon7);
        teaching_18->setIconSize(QSize(40, 40));
        teaching_18->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_19 = new QToolButton(centralWidget);
        teaching_19->setObjectName(QStringLiteral("teaching_19"));
        teaching_19->setEnabled(true);
        teaching_19->setGeometry(QRect(990, 290, 50, 50));
        teaching_19->setAutoFillBackground(false);
        teaching_19->setIcon(icon7);
        teaching_19->setIconSize(QSize(40, 40));
        teaching_19->setToolButtonStyle(Qt::ToolButtonIconOnly);
        teaching_20 = new QToolButton(centralWidget);
        teaching_20->setObjectName(QStringLiteral("teaching_20"));
        teaching_20->setEnabled(true);
        teaching_20->setGeometry(QRect(1000, 300, 50, 50));
        teaching_20->setAutoFillBackground(false);
        teaching_20->setIcon(icon7);
        teaching_20->setIconSize(QSize(40, 40));
        teaching_20->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_2 = new QToolButton(centralWidget);
        dorm_2->setObjectName(QStringLiteral("dorm_2"));
        dorm_2->setEnabled(true);
        dorm_2->setGeometry(QRect(890, 110, 50, 50));
        dorm_2->setAutoFillBackground(false);
        dorm_2->setIcon(icon6);
        dorm_2->setIconSize(QSize(40, 40));
        dorm_2->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_3 = new QToolButton(centralWidget);
        dorm_3->setObjectName(QStringLiteral("dorm_3"));
        dorm_3->setEnabled(true);
        dorm_3->setGeometry(QRect(910, 130, 50, 50));
        dorm_3->setAutoFillBackground(false);
        dorm_3->setIcon(icon6);
        dorm_3->setIconSize(QSize(40, 40));
        dorm_3->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_4 = new QToolButton(centralWidget);
        dorm_4->setObjectName(QStringLiteral("dorm_4"));
        dorm_4->setEnabled(true);
        dorm_4->setGeometry(QRect(920, 140, 50, 50));
        dorm_4->setAutoFillBackground(false);
        dorm_4->setIcon(icon6);
        dorm_4->setIconSize(QSize(40, 40));
        dorm_4->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_5 = new QToolButton(centralWidget);
        dorm_5->setObjectName(QStringLiteral("dorm_5"));
        dorm_5->setEnabled(true);
        dorm_5->setGeometry(QRect(930, 150, 50, 50));
        dorm_5->setAutoFillBackground(false);
        dorm_5->setIcon(icon6);
        dorm_5->setIconSize(QSize(40, 40));
        dorm_5->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_6 = new QToolButton(centralWidget);
        dorm_6->setObjectName(QStringLiteral("dorm_6"));
        dorm_6->setEnabled(true);
        dorm_6->setGeometry(QRect(940, 160, 50, 50));
        dorm_6->setAutoFillBackground(false);
        dorm_6->setIcon(icon6);
        dorm_6->setIconSize(QSize(40, 40));
        dorm_6->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_7 = new QToolButton(centralWidget);
        dorm_7->setObjectName(QStringLiteral("dorm_7"));
        dorm_7->setEnabled(true);
        dorm_7->setGeometry(QRect(950, 170, 50, 50));
        dorm_7->setAutoFillBackground(false);
        dorm_7->setIcon(icon6);
        dorm_7->setIconSize(QSize(40, 40));
        dorm_7->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_8 = new QToolButton(centralWidget);
        dorm_8->setObjectName(QStringLiteral("dorm_8"));
        dorm_8->setEnabled(true);
        dorm_8->setGeometry(QRect(960, 180, 50, 50));
        dorm_8->setAutoFillBackground(false);
        dorm_8->setIcon(icon6);
        dorm_8->setIconSize(QSize(40, 40));
        dorm_8->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_9 = new QToolButton(centralWidget);
        dorm_9->setObjectName(QStringLiteral("dorm_9"));
        dorm_9->setEnabled(true);
        dorm_9->setGeometry(QRect(970, 190, 50, 50));
        dorm_9->setAutoFillBackground(false);
        dorm_9->setIcon(icon6);
        dorm_9->setIconSize(QSize(40, 40));
        dorm_9->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_10 = new QToolButton(centralWidget);
        dorm_10->setObjectName(QStringLiteral("dorm_10"));
        dorm_10->setEnabled(true);
        dorm_10->setGeometry(QRect(980, 200, 50, 50));
        dorm_10->setAutoFillBackground(false);
        dorm_10->setIcon(icon6);
        dorm_10->setIconSize(QSize(40, 40));
        dorm_10->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_11 = new QToolButton(centralWidget);
        dorm_11->setObjectName(QStringLiteral("dorm_11"));
        dorm_11->setEnabled(true);
        dorm_11->setGeometry(QRect(990, 210, 50, 50));
        dorm_11->setAutoFillBackground(false);
        dorm_11->setIcon(icon6);
        dorm_11->setIconSize(QSize(40, 40));
        dorm_11->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_12 = new QToolButton(centralWidget);
        dorm_12->setObjectName(QStringLiteral("dorm_12"));
        dorm_12->setEnabled(true);
        dorm_12->setGeometry(QRect(1000, 220, 50, 50));
        dorm_12->setAutoFillBackground(false);
        dorm_12->setIcon(icon6);
        dorm_12->setIconSize(QSize(40, 40));
        dorm_12->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_13 = new QToolButton(centralWidget);
        dorm_13->setObjectName(QStringLiteral("dorm_13"));
        dorm_13->setEnabled(true);
        dorm_13->setGeometry(QRect(1010, 230, 50, 50));
        dorm_13->setAutoFillBackground(false);
        dorm_13->setIcon(icon6);
        dorm_13->setIconSize(QSize(40, 40));
        dorm_13->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_14 = new QToolButton(centralWidget);
        dorm_14->setObjectName(QStringLiteral("dorm_14"));
        dorm_14->setEnabled(true);
        dorm_14->setGeometry(QRect(1020, 240, 50, 50));
        dorm_14->setAutoFillBackground(false);
        dorm_14->setIcon(icon6);
        dorm_14->setIconSize(QSize(40, 40));
        dorm_14->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_15 = new QToolButton(centralWidget);
        dorm_15->setObjectName(QStringLiteral("dorm_15"));
        dorm_15->setEnabled(true);
        dorm_15->setGeometry(QRect(1030, 250, 50, 50));
        dorm_15->setAutoFillBackground(false);
        dorm_15->setIcon(icon6);
        dorm_15->setIconSize(QSize(40, 40));
        dorm_15->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_16 = new QToolButton(centralWidget);
        dorm_16->setObjectName(QStringLiteral("dorm_16"));
        dorm_16->setEnabled(true);
        dorm_16->setGeometry(QRect(1040, 260, 50, 50));
        dorm_16->setAutoFillBackground(false);
        dorm_16->setIcon(icon6);
        dorm_16->setIconSize(QSize(40, 40));
        dorm_16->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_17 = new QToolButton(centralWidget);
        dorm_17->setObjectName(QStringLiteral("dorm_17"));
        dorm_17->setEnabled(true);
        dorm_17->setGeometry(QRect(1050, 270, 50, 50));
        dorm_17->setAutoFillBackground(false);
        dorm_17->setIcon(icon6);
        dorm_17->setIconSize(QSize(40, 40));
        dorm_17->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_18 = new QToolButton(centralWidget);
        dorm_18->setObjectName(QStringLiteral("dorm_18"));
        dorm_18->setEnabled(true);
        dorm_18->setGeometry(QRect(1060, 280, 50, 50));
        dorm_18->setAutoFillBackground(false);
        dorm_18->setIcon(icon6);
        dorm_18->setIconSize(QSize(40, 40));
        dorm_18->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_19 = new QToolButton(centralWidget);
        dorm_19->setObjectName(QStringLiteral("dorm_19"));
        dorm_19->setEnabled(true);
        dorm_19->setGeometry(QRect(1070, 290, 50, 50));
        dorm_19->setAutoFillBackground(false);
        dorm_19->setIcon(icon6);
        dorm_19->setIconSize(QSize(40, 40));
        dorm_19->setToolButtonStyle(Qt::ToolButtonIconOnly);
        dorm_20 = new QToolButton(centralWidget);
        dorm_20->setObjectName(QStringLiteral("dorm_20"));
        dorm_20->setEnabled(true);
        dorm_20->setGeometry(QRect(1080, 300, 50, 50));
        dorm_20->setAutoFillBackground(false);
        dorm_20->setIcon(icon6);
        dorm_20->setIconSize(QSize(40, 40));
        dorm_20->setToolButtonStyle(Qt::ToolButtonIconOnly);
        DigitalMapForWHUClass->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(DigitalMapForWHUClass);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 2000, 19));
        DigitalMapForWHUClass->setMenuBar(menuBar);
        mainToolBar = new QToolBar(DigitalMapForWHUClass);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        mainToolBar->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        DigitalMapForWHUClass->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(DigitalMapForWHUClass);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        DigitalMapForWHUClass->setStatusBar(statusBar);

        mainToolBar->addAction(actionquery);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionroute);
        mainToolBar->addAction(actionaddress);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionexit);

        retranslateUi(DigitalMapForWHUClass);

        QMetaObject::connectSlotsByName(DigitalMapForWHUClass);
    } // setupUi

    void retranslateUi(QMainWindow *DigitalMapForWHUClass)
    {
        DigitalMapForWHUClass->setWindowTitle(QApplication::translate("DigitalMapForWHUClass", "DigitalMapForWHU", nullptr));
        actionquery->setText(QApplication::translate("DigitalMapForWHUClass", "\346\237\245\350\257\242", nullptr));
#ifndef QT_NO_TOOLTIP
        actionquery->setToolTip(QApplication::translate("DigitalMapForWHUClass", "\346\237\245\350\257\242", nullptr));
#endif // QT_NO_TOOLTIP
        actionexit->setText(QApplication::translate("DigitalMapForWHUClass", "\351\200\200\345\207\272", nullptr));
#ifndef QT_NO_TOOLTIP
        actionexit->setToolTip(QApplication::translate("DigitalMapForWHUClass", "\351\200\200\345\207\272", nullptr));
#endif // QT_NO_TOOLTIP
        actionroute->setText(QApplication::translate("DigitalMapForWHUClass", "\346\234\200\347\237\255\350\267\257\345\276\204", nullptr));
#ifndef QT_NO_TOOLTIP
        actionroute->setToolTip(QApplication::translate("DigitalMapForWHUClass", "\346\234\200\347\237\255\350\267\257\345\276\204", nullptr));
#endif // QT_NO_TOOLTIP
        actionaddress->setText(QApplication::translate("DigitalMapForWHUClass", "\350\266\205\345\270\202\351\200\211\345\235\200", nullptr));
#ifndef QT_NO_TOOLTIP
        actionaddress->setToolTip(QApplication::translate("DigitalMapForWHUClass", "\350\266\205\345\270\202\351\200\211\345\235\200", nullptr));
#endif // QT_NO_TOOLTIP
        office_1->setText(QString());
        canteen_1->setText(QString());
        dorm_1->setText(QString());
        teaching_1->setText(QString());
        canteen_2->setText(QString());
        canteen_3->setText(QString());
        canteen_4->setText(QString());
        canteen_5->setText(QString());
        canteen_6->setText(QString());
        canteen_7->setText(QString());
        canteen_8->setText(QString());
        canteen_9->setText(QString());
        canteen_10->setText(QString());
        canteen_11->setText(QString());
        canteen_12->setText(QString());
        canteen_13->setText(QString());
        canteen_14->setText(QString());
        canteen_15->setText(QString());
        canteen_16->setText(QString());
        canteen_17->setText(QString());
        canteen_18->setText(QString());
        canteen_19->setText(QString());
        canteen_20->setText(QString());
        office_2->setText(QString());
        office_3->setText(QString());
        office_4->setText(QString());
        office_5->setText(QString());
        office_6->setText(QString());
        office_7->setText(QString());
        office_8->setText(QString());
        office_9->setText(QString());
        office_10->setText(QString());
        office_11->setText(QString());
        office_12->setText(QString());
        office_13->setText(QString());
        office_14->setText(QString());
        office_15->setText(QString());
        office_16->setText(QString());
        office_17->setText(QString());
        office_18->setText(QString());
        office_19->setText(QString());
        office_20->setText(QString());
        teaching_2->setText(QString());
        teaching_3->setText(QString());
        teaching_4->setText(QString());
        teaching_5->setText(QString());
        teaching_6->setText(QString());
        teaching_7->setText(QString());
        teaching_8->setText(QString());
        teaching_9->setText(QString());
        teaching_10->setText(QString());
        teaching_11->setText(QString());
        teaching_12->setText(QString());
        teaching_13->setText(QString());
        teaching_14->setText(QString());
        teaching_15->setText(QString());
        teaching_16->setText(QString());
        teaching_17->setText(QString());
        teaching_18->setText(QString());
        teaching_19->setText(QString());
        teaching_20->setText(QString());
        dorm_2->setText(QString());
        dorm_3->setText(QString());
        dorm_4->setText(QString());
        dorm_5->setText(QString());
        dorm_6->setText(QString());
        dorm_7->setText(QString());
        dorm_8->setText(QString());
        dorm_9->setText(QString());
        dorm_10->setText(QString());
        dorm_11->setText(QString());
        dorm_12->setText(QString());
        dorm_13->setText(QString());
        dorm_14->setText(QString());
        dorm_15->setText(QString());
        dorm_16->setText(QString());
        dorm_17->setText(QString());
        dorm_18->setText(QString());
        dorm_19->setText(QString());
        dorm_20->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class DigitalMapForWHUClass: public Ui_DigitalMapForWHUClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DIGITALMAPFORWHU_H
